name: main-pipeline

permissions:
  contents: read
  security-events: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: CodeQL Init
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: CodeQL Analyze
        uses: github/codeql-action/analyze@v3

      - name: Bump version
        id: bump
        run: |
          chmod +x scripts/bump_version.sh
          newver=$(./scripts/bump_version.sh | grep "New version" | awk '{print $3}')
          echo "version=$newver" >> $GITHUB_OUTPUT

      - name: AI Summary
        run: |
          echo "AI Summary: (Mock) Summarizing changes in main..."
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Build Docker
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build --build-arg NODE_ENV=production -t ghcr.io/$REPO:main-${{ steps.bump.outputs.version }} .
          docker tag ghcr.io/$REPO:main-${{ steps.bump.outputs.version }} ghcr.io/$REPO:latest

      - name: Login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$REPO:main-${{ steps.bump.outputs.version }}
          docker push ghcr.io/$REPO:latest
